# renew_before_expiry = 30 days
version = 1.21.0
archive_dir = /etc/letsencrypt/archive/test-devops.vizorlabs.tech
cert = /etc/letsencrypt/live/test-devops.vizorlabs.tech/cert.pem
privkey = /etc/letsencrypt/live/test-devops.vizorlabs.tech/privkey.pem
chain = /etc/letsencrypt/live/test-devops.vizorlabs.tech/chain.pem
fullchain = /etc/letsencrypt/live/test-devops.vizorlabs.tech/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 965a5591386bd0e8b9092fb5800a292b
authenticator = webroot
webroot_path = /home/devops/flaskApp/certbot/www,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
test-devops.vizorlabs.tech = /home/devops/flaskApp/certbot/www
